general {
    hide_cursor = true
    ignore_empty_input = true
    immediate_render = true
}

animations {
    enabled = false
}

$font = Noto Sans UI

background {
    monitor =
    path = /home/ajani/.local/state/awww/lockwall
    color = rgba(1e1e1eFF)
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# Clock
label {
    monitor =
    text = $TIME
    font_size = 88
    font_family = $font
    color = rgba(ffffffff)
    position = 0, 200
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.6
    outer_color = rgba(ffffffff)
    inner_color = rgba(000000cc)
    font_color = rgba(ffffffff)
    fade_on_empty = true
    placeholder_text = <i><span foreground="##ffffff">Password...</span></i>
    hide_input = false
    position = 0, -80
    halign = center
    valign = center
}
