general {
    lock_cmd = pidof hyprlock || /home/ajani/.config/hypr/lockwall.sh
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
    timeout = 300
    on_timeout = loginctl lock-session
}

listener {
    timeout = 330
    on_timeout = hyprctl dispatch dpms off
}

listener {
    timeout = 600
    on_timeout = systemctl suspend
}