-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Breeze_Light")
hl.env("XCURSOR_SIZE", "24")

-- Settings
hl.config({
    decoration = {
        blur = {
            size = 5,
            xray = true,
        },
        shadow = {
            enabled = false,
        },
    },
    ecosystem = {
        no_donation_nag = true,
    },
    general = {
        gaps_out = 10,
        resize_on_border = true,
    },
    gestures = {
        workspace_swipe_forever = false,
        workspace_swipe_use_r = false,
    },
    input = {
        touchpad = {
            natural_scroll = true,
        },
    },
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
    },
})

-- Animations
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 3.0,
    bezier = "default",
})
hl.animation({
    leaf = "windowsIn",
    enabled = true,
    speed = 3.0,
    bezier = "default",
    style = "slide",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 3.0,
    bezier = "default",
    style = "slide",
})
hl.animation({
    leaf = "windowsMove",
    enabled = true,
    speed = 3.0,
    bezier = "default",
})
hl.animation({
    leaf = "layers",
    enabled = true,
    speed = 3.0,
    bezier = "default",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 3.0,
    bezier = "default",
})
hl.animation({
    leaf = "workspaces",
    enabled = false,
})
